### ISSUE TITLE
Issue to run your code

### ISSUE THREAD

**Issue by patrickhener** [nluede/cvdarts#1]
Hi Niels,

I got the first issue to report. Wanted to test it and discovered the following when running `python3 setup.py install`

```
--- python-prj/cvDarts ‹master* M› » python3 setup.py        
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    packages=['cvdarts'], requires=['opencv-python', 'numpy']
  File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.7/distutils/dist.py", line 267, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python3.7/distutils/dist.py", line 1227, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python3.7/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-python'
```

Maybe you know what's going on?

**Comment by patrickhener** [comment]
I tried the current version again with two webcams and I am not able to get results.
I tried to configure it using `--config 0 2` (which are my videoX ids). In the configure dialog only cam with ID 0 is shown. If I configure them using `--config 0` first then `--config 2` it will show cam1 and cam2 just right.
When looking at the database it is still empty. Is there supposed to be data?
Also when running main.py with arguments `0 2` it will show the two webcam windows. But it will not recognize any darts movement. Is there something I can do to debug?

Thanks in advance,
Patrick

**Comment by patrickhener** [comment]
Reopen!

**Comment by patrickhener** [comment]
So I was able to run it now! Not easy but with a little debugging I figured I have to use `j` and `k` and `q` to calibrate. Then the configuration is saved just fine and the main function runs. I have serious trouble with threshold though and my darts are not very good recognized at all. Maybe of them being silver and white and really slim. I tried my softdarts which are black and red and a little bit bulkier. Used some conversion point tips. They are recognized better. Is there a good way to tweak settings to better recognize the darts? There is also some serious lag going on it seams.
What are the next steps for actually recognizing which number and modifiers were hit?
Best regards,
Patrick
